### ISSUE TITLE
No package available for Windows

### ISSUE THREAD

**Issue by blowekamp** [conda-forge/lua-feedstock#20]
I am in need of using lua on windows for a recipe build dependency: conda-forge/staged-recipes#2846

For out project we can build Lua as a dependency if needed. We have a local[ CMakeLists.txt](https://github.com/SimpleITK/SimpleITK/blob/next/SuperBuild/lua.cmake) script which is portable. It might be able to be re-used here. Please let me know if I can do anything to assist.

**Comment by jakirkham** [comment]
Well, as far as I know, this feedstock is unmaintained. Am basing that on this [comment]( https://github.com/conda-forge/lua-feedstock/pull/16#issuecomment-270171606 ) from the original maintainer. Would you be willing to maintain this feedstock? If not, I completely understand, but I don't think Windows support will be taken up otherwise.

**Comment by seanyen** [comment]
@jakirkham @blowekamp It has been two years late, but #29 should enable the Windows build. I am willing to maintain this feedstock and let me know how I can move this forward.

**Comment by wolfv** [comment]
This seems solved now. Thanks to @seanyen
